# ./scripts/Dockerfile.archiver
FROM python:3.12-slim

# Set working directory
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y curl iputils-ping && rm -rf /var/lib/apt/lists/*

# Copy archiver script
COPY archive_orders.py /app/

# Install required Python packages
RUN pip install pymongo hdfs

# Command to run the archiver
CMD ["python", "archive_orders.py"]
